"""Offline: read pack_archetype_map.json + old_archetypes.json, emit
ap_world/data/pack_archetypes.py.

Two outputs baked into the apworld:

  PACK_ARCHETYPES: dict[str, list[str]]
    Pack item name -> canonical display names of archetypes in that pack.
    Keys match `PACK_ITEM_TO_BIT` keys in ap_world/items.py (i.e. include the
    " Pack" suffix). Values are deduped, source-order preserved.

  ARCHETYPE_CARDS: dict[str, list[int]]
    Canonical display name -> sorted list of card indices belonging to that
    archetype. Multiple enums sharing a display name (e.g. RedDemon and
    Resonator -> "Red Dragon Archfiend") are unioned. Indices are filtered to
    those present in ap_world/data/card_list.py::BY_INDEX.

Run after curating pack_archetype_map.json. Not part of the normal apworld
build.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
PACK_MAP_JSON = HERE / "pack_archetype_map.json"
OLD_ARCH_JSON = HERE / "old_archetypes.json"
OUT_PATH = REPO / "ap_world" / "data" / "pack_archetypes.py"

# Archetypes with fewer than this many unique cards in BY_INDEX are dropped at
# build time — they're too small to support the starter-archetype grant
# (8 unique cards × 3 copies). The prune happens after multi-enum union, so
# small individual enums can still survive if they share a display name with
# a larger enum.
MIN_ARCHETYPE_CARDS = 7

# Load card_list as a standalone module to skip ap_world __init__'s import of
# Archipelago's `worlds` package.
_CARD_LIST_PATH = REPO / "ap_world" / "data" / "card_list.py"
_spec = importlib.util.spec_from_file_location("card_list", _CARD_LIST_PATH)
_card_list = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_card_list)
BY_INDEX: dict[int, dict] = _card_list.BY_INDEX


def build() -> tuple[dict[str, list[str]], dict[str, list[int]]]:
    pack_map = json.loads(PACK_MAP_JSON.read_text(encoding="utf-8"))
    enum_to_cards: dict[str, list[int]] = (
        json.loads(OLD_ARCH_JSON.read_text(encoding="utf-8"))["archetypes"]
    )

    pack_archetypes: dict[str, list[str]] = {}
    archetype_cards: dict[str, set[int]] = {}
    missing_enums: set[str] = set()

    for pack in pack_map.get("packs", []):
        pack_name = pack["name"]
        displays_seen: list[str] = []
        for entry in pack.get("archetypes", []):
            if isinstance(entry, str):
                enum_name, display = entry, entry
            else:
                enum_name = entry["enum"]
                display = entry.get("display") or enum_name
            if display not in displays_seen:
                displays_seen.append(display)
            cards = enum_to_cards.get(enum_name)
            if cards is None:
                missing_enums.add(enum_name)
                continue
            bucket = archetype_cards.setdefault(display, set())
            for cid in cards:
                if cid in BY_INDEX:
                    bucket.add(cid)
        pack_archetypes[pack_name] = displays_seen

    if missing_enums:
        print(
            f"WARN: {len(missing_enums)} enum name(s) not in old_archetypes.json: "
            f"{sorted(missing_enums)[:10]}{'...' if len(missing_enums) > 10 else ''}",
            file=sys.stderr,
        )

    # Prune archetypes too small to be a viable starter pick. Drop them from
    # both ARCHETYPE_CARDS and from each pack's display list. Fail loudly if
    # this would leave any pack with zero archetypes — the starter-pick gate
    # has no fallback path.
    too_small = {
        d for d, cards in archetype_cards.items()
        if len(cards) < MIN_ARCHETYPE_CARDS
    }
    if too_small:
        for d in too_small:
            del archetype_cards[d]
        emptied: list[str] = []
        for pack_name, displays in list(pack_archetypes.items()):
            kept = [d for d in displays if d not in too_small]
            pack_archetypes[pack_name] = kept
            if not kept:
                emptied.append(pack_name)
        if emptied:
            raise RuntimeError(
                f"prune left these packs with no archetypes: {emptied}. "
                f"Lower MIN_ARCHETYPE_CARDS or add larger archetypes to "
                f"pack_archetype_map.json for those packs."
            )
        print(
            f"  pruned {len(too_small)} archetype(s) with < "
            f"{MIN_ARCHETYPE_CARDS} cards"
        )

    archetype_cards_sorted = {
        k: sorted(v) for k, v in sorted(archetype_cards.items())
    }
    return pack_archetypes, archetype_cards_sorted


def emit(pack_archetypes: dict[str, list[str]],
         archetype_cards: dict[str, list[int]]) -> None:
    lines: list[str] = []
    lines.append('"""Auto-generated by debug_tools/build_pack_archetypes.py.')
    lines.append("")
    lines.append("Do not edit by hand — re-run the builder after editing")
    lines.append("debug_tools/pack_archetype_map.json.")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("# Pack item name (with ' Pack' suffix, matches PACK_ITEM_TO_BIT keys")
    lines.append("# in ap_world/items.py) -> canonical archetype display names.")
    lines.append("PACK_ARCHETYPES: dict[str, list[str]] = {")
    for pack_name, displays in pack_archetypes.items():
        joined = ", ".join(repr(d) for d in displays)
        lines.append(f"    {pack_name!r}: [{joined}],")
    lines.append("}")
    lines.append("")
    lines.append("# Canonical archetype display name -> sorted list of card indices")
    lines.append("# (LOTD-LE internal indices, matching ap_world/data/card_list.py::BY_INDEX).")
    lines.append("# Enums sharing a display name are unioned here.")
    lines.append("ARCHETYPE_CARDS: dict[str, list[int]] = {")
    for display, indices in archetype_cards.items():
        if len(indices) <= 12:
            ids = ", ".join(str(i) for i in indices)
            lines.append(f"    {display!r}: [{ids}],")
        else:
            lines.append(f"    {display!r}: [")
            for i in range(0, len(indices), 12):
                chunk = ", ".join(str(x) for x in indices[i:i + 12])
                lines.append(f"        {chunk},")
            lines.append("    ],")
    lines.append("}")
    lines.append("")
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not PACK_MAP_JSON.is_file():
        print(f"missing {PACK_MAP_JSON}", file=sys.stderr)
        return 1
    if not OLD_ARCH_JSON.is_file():
        print(f"missing {OLD_ARCH_JSON}", file=sys.stderr)
        return 1
    pack_archetypes, archetype_cards = build()
    emit(pack_archetypes, archetype_cards)

    total_archs = sum(len(v) for v in pack_archetypes.values())
    distinct = len(archetype_cards)
    total_cards = sum(len(v) for v in archetype_cards.values())
    empty_packs = [k for k, v in pack_archetypes.items() if not v]
    empty_archs = [k for k, v in archetype_cards.items() if not v]
    print(f"wrote {OUT_PATH}")
    print(f"  packs: {len(pack_archetypes)} ({total_archs} archetype refs)")
    print(f"  distinct archetypes: {distinct}")
    print(f"  total card-index rows: {total_cards}")
    if empty_packs:
        print(f"  WARN: {len(empty_packs)} pack(s) have no archetypes: {empty_packs}")
    if empty_archs:
        print(f"  WARN: {len(empty_archs)} archetype(s) have no cards in BY_INDEX: {empty_archs[:10]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
